---
- hosts: all
  become: yes
  tasks:
    - name: Task - 1 Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Task -2 Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
    - name: "copying ui code"
      become: true 
      copy:
        src: /etc/ansible/service-catalogue-services-1.0.0.jar
        dest: /home/ansadmin/
    - name: installing server
      shell: java -jar service-catalogue-services-1.0.0.jar    
