- hosts: all
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

# - name: "copy ui code"
#   file:
#      path: /var/www/{{ domain }}
#      state: directory
#      mode: '0775'
#      owner: "{{ ansible_user }}"
#      group: "{{ ansible_user }}"
  
  - name: "copying ui code"
    become: true 
    copy:
      src: /etc/ansible/service-catalogue-ui-1.0.0/
      dest: /var/www/html
      owner: ansadmin
      group: ansadmin        
      mode: 0775

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: service.conf
      dest: /etc/nginx/sites-enabled/
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
